// Provision Data Libraries
// Copyright (C) 2026 Provision Data Systems Inc.
//
// This program is free software: you can redistribute it and/or modify it under the terms of
// the GNU Affero General Public License as published by the Free Software Foundation, either
// version 3 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY
// without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
// See the GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License along with this
// program. If not, see <https://www.gnu.org/licenses/>.

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

namespace ProvisionData.ResultPattern;

[Generator]
public sealed class ErrorSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // STEP 1: Find all class declarations with "partial" and ": Error"
        var errorClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidate(node),
                transform: static (ctx, _) => GetErrorSymbol(ctx))
            .Where(static m => m is not null);

        // STEP 2: Collect them into an array
        var collected = errorClasses.Collect();

        // STEP 3: Generate code
        context.RegisterSourceOutput(collected, static (spc, errors) =>
        {
            GenerateErrorCodes(spc, errors!);
            GenerateConstructors(spc, errors!);
            GenerateRegistry(spc, errors!);
        });
    }

    private static Boolean IsCandidate(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax cds
            && cds.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword));
    }

    private static INamedTypeSymbol? GetErrorSymbol(GeneratorSyntaxContext ctx)
    {
        var cds = (ClassDeclarationSyntax)ctx.Node;

        if (ctx.SemanticModel.GetDeclaredSymbol(cds) is not INamedTypeSymbol symbol)
        {
            return null;
        }

        // Must derive from Error
        var baseType = symbol.BaseType;

        while (baseType is not null)
        {
            var fullName = baseType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            if (fullName == "global::ProvisionData.ResultPattern.Error")
            {
                return symbol;
            }

            baseType = baseType.BaseType;
        }

        return null;
    }

    private static void GenerateErrorCodes(SourceProductionContext context, ImmutableArray<INamedTypeSymbol> errors)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine();

        foreach (var error in errors)
        {
            var ns = error.ContainingNamespace.IsGlobalNamespace
                ? null
                : error.ContainingNamespace.ToDisplayString();

            var errorName = error.Name;
            var codeName = errorName + "Code";

            if (ns is not null)
            {
                sb.AppendLine($"namespace {ns}");
                sb.AppendLine("{");
            }

            sb.AppendLine($"#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member");
            sb.AppendLine($"internal sealed class {codeName} : ProvisionData.ResultPattern.ErrorCode");
            sb.AppendLine("{");
            sb.AppendLine($"    public static readonly {codeName} Instance = new();");
            sb.AppendLine($"    protected override System.String Name => \"{errorName}\";");
            sb.AppendLine("}");
            sb.AppendLine($"#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member");

            if (ns is not null)
            {
                sb.AppendLine("}");
            }
            sb.AppendLine();
        }

        context.AddSource("ErrorCodes.g.cs", sb.ToString());
    }

    private static void GenerateConstructors(SourceProductionContext context, ImmutableArray<INamedTypeSymbol> errors)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine();

        foreach (var error in errors)
        {
            var ns = error.ContainingNamespace.IsGlobalNamespace
                ? null
                : error.ContainingNamespace.ToDisplayString();

            var errorName = error.Name;
            var codeName = errorName + "Code";

            // Find all properties (typically marked with 'required')
            var properties = error.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => !p.IsStatic && p.SetMethod is not null)
                .ToList();

            if (ns is not null)
            {
                sb.AppendLine($"namespace {ns}");
                sb.AppendLine("{");
            }

            sb.AppendLine($"#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member");
            sb.AppendLine($"public sealed partial class {errorName}");
            sb.AppendLine("{");

            // Generate constructor
            sb.AppendLine($"    public {errorName}(");

            // Build parameter list from properties
            var paramList = new List<String>();
            foreach (var prop in properties)
            {
                var type = prop.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
                var paramName = LowerFirst(prop.Name);
                paramList.Add($"{type} {paramName}");
            }
            paramList.Add("System.String description");

            sb.AppendLine($"        {String.Join(",\r\n        ", paramList)})");
            sb.AppendLine($"        : base({codeName}.Instance, description)");
            sb.AppendLine("    {");

            // Initialize properties from parameters
            foreach (var prop in properties)
            {
                var paramName = LowerFirst(prop.Name);
                sb.AppendLine($"        this.{prop.Name} = {paramName};");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine($"#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member");

            if (ns is not null)
            {
                sb.AppendLine("}");
            }
            sb.AppendLine();
        }

        context.AddSource("ErrorConstructors.g.cs", sb.ToString());
    }

    private static String LowerFirst(String name)
        => String.IsNullOrEmpty(name) ? name : Char.ToLowerInvariant(name[0]) + name.Substring(1);

    private static void GenerateRegistry(SourceProductionContext context, ImmutableArray<INamedTypeSymbol> errors)
    {
        if (errors.Length == 0)
        {
            return; // No errors to register
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        
        // Get the namespace of the first error (they should all be in the same assembly)
        var ns = errors[0].ContainingNamespace.IsGlobalNamespace
            ? null
            : errors[0].ContainingNamespace.ToDisplayString();

        if (ns is not null)
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }

        sb.AppendLine("#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member");
        sb.AppendLine("internal static class ErrorTypeRegistryInitializer");
        sb.AppendLine("{");
        sb.AppendLine("    [System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    internal static void Initialize()");
        sb.AppendLine("    {");

        foreach (var error in errors)
        {
            var fullName = error.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                .Replace("global::", "");
            sb.AppendLine($"        ProvisionData.ResultPattern.ErrorTypeRegistry.Register<{fullName}>();");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine("#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member");

        if (ns is not null)
        {
            sb.AppendLine("}");
        }

        context.AddSource("ErrorTypeRegistryInitializer.g.cs", sb.ToString());
    }

    private static String UpperFirst(String name)
        => String.IsNullOrEmpty(name) ? name : Char.ToUpperInvariant(name[0]) + name.Substring(1);
}
