<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace />
		<TargetFrameworks>net8.0;net10.0</TargetFrameworks>

		<!-- NuGet package metadata -->
		<PackageId>ProvisionData.Common</PackageId>
		<Title>Provision Data Core Library</Title>
		<Description>Basic classes and utilities used across all PDSI projects.</Description>
		<PackageTags></PackageTags>
		<PackageReadmeFile>./README.md</PackageReadmeFile>
		<GenerateDocumentationFile>false</GenerateDocumentationFile>
		<IsPackable>true</IsPackable>
		<IsAotCompatible>false</IsAotCompatible>
		<IsTrimmable>true</IsTrimmable>
	</PropertyGroup>

	<ItemGroup>
		<None Include="./README.md" Pack="true" PackagePath="/" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="ILLink.Descriptors.xml">
			<LogicalName>ILLink.Descriptors.xml</LogicalName>
		</EmbeddedResource>
	</ItemGroup>

</Project>
