// ProvisionData.Common
// Copyright (C) 2026 Provision Data Systems Inc.
//
// This program is free software: you can redistribute it and/or modify it under the terms of
// the GNU Affero General Public License as published by the Free Software Foundation, either
// version 3 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY
// without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
// See the GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License along with this
// program. If not, see <https://www.gnu.org/licenses/>.

using System.Collections.Concurrent;
using System.Diagnostics.CodeAnalysis;
using System.Reflection;

namespace ProvisionData.Versioning;

/// <summary>
/// Provides access to assembly version information generated by NerdBank.GitVersioning.
/// </summary>
public sealed class VersionInfo
{
    private static readonly ConcurrentDictionary<Type, VersionInfo?> Versions = new();

    [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicFields | DynamicallyAccessedMemberTypes.NonPublicFields)]
    private readonly Type _type;

    /// <summary>
    /// Attempts to retrieve the <see cref="VersionInfo"/> for the assembly containing <typeparamref name="T"/>.
    /// </summary>
    /// <typeparam name="T">The type whose containing assembly is used to obtain version information.</typeparam>
    /// <returns><see cref="VersionInfo"/> if it exists; otherwise <see langword="null"/>.</returns>
    /// <remarks>
    /// The result is cached based on the type <typeparamref name="T"/> to optimize repeated calls.
    /// </remarks>
    public static VersionInfo? ForAssemblyContaining<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] T>()
    {
        // This line ensures that NerdBank.GitVersioning has been configured in this assembly.
        // It also forces the linker to preserve ThisAssembly type and its members.
        _ = ThisAssembly.AssemblyConfiguration;

        var key = typeof(T);
        return Versions.GetOrAdd(key, type =>
        {
            var versionInfo = ForAssembly(type.Assembly);

            // We cache the the VersionInfo if found; otherwise we cache the null to avoid repeated reflection.
            return versionInfo;
        });
    }

    /// <summary>
    /// Retrieves the <see cref="VersionInfo"/> for the specified <paramref name="assembly"/>.
    /// </summary>
    /// <param name="assembly">The assembly from which to retrieve version information. Cannot be null.</param>
    /// <returns>A <see cref="VersionInfo"/> instance containing version information if a type named "ThisAssembly" is found in the assembly; otherwise, <see langword="null"/>.</returns>
    /// <remarks>
    /// This method relies on the presence of a type named "ThisAssembly" in the provided assembly,
    /// which is typically generated by the NerdBank.GitVersioning build tool to hold version metadata.
    /// If the type is not present, the method returns <see langword="null"/> instead of throwing an exception.
    /// </remarks>
    [UnconditionalSuppressMessage("Trimming", "IL2026:Members annotated with 'RequiresUnreferencedCodeAttribute' require dynamic access otherwise can break functionality when trimming application code", Justification = "This method searches for a well-known type 'ThisAssembly' generated by NerdBank.GitVersioning which is always preserved")]
    [UnconditionalSuppressMessage("Trimming", "IL2072:Target parameter argument does not satisfy 'DynamicallyAccessedMembersAttribute' in call to target method", Justification = "The ThisAssembly type generated by NerdBank.GitVersioning has the required public and non-public fields preserved")]
    public static VersionInfo? ForAssembly(Assembly assembly)
    {
        ArgumentNullException.ThrowIfNull(assembly);

        var typeInfo = assembly.DefinedTypes.SingleOrDefault(t => String.Equals(t.Name, "ThisAssembly", StringComparison.InvariantCulture));

        // Not finding the ThisAssembly type is a normal condition, not a reason to throw.
        return typeInfo is null ? null : new VersionInfo(assembly, typeInfo.AsType());
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="VersionInfo"/> class.
    /// </summary>
    /// <param name="assembly">The assembly containing version information.</param>
    /// <param name="type">The type containing version metadata fields.</param>
    /// <exception cref="ArgumentNullException"><paramref name="assembly"/> or <paramref name="type"/> is <see langword="null"/>.</exception>
    [SuppressMessage("SingleFile", "IL3000:Avoid accessing Assembly file path when publishing as a single file", Justification = "An empty string is not a problem.")]
    private VersionInfo(Assembly assembly, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicFields | DynamicallyAccessedMemberTypes.NonPublicFields)] Type type)
    {
        ArgumentNullException.ThrowIfNull(assembly);

        _type = type ?? throw new ArgumentNullException(nameof(type));

        AssemblyFullName = assembly.FullName!;
        AssemblyName = AssemblyFullName.Split([',', ' '], StringSplitOptions.RemoveEmptyEntries)[0];
        AssemblyImageRuntimeVersion = assembly.ImageRuntimeVersion;
        AssemblyLocation = assembly.Location;
    }

    /// <summary>
    /// Retrieves a value from the ThisAssembly type's static fields.
    /// </summary>
    /// <typeparam name="T">The type of value to retrieve.</typeparam>
    /// <param name="name">The name of the static field.</param>
    /// <returns>The field value, or the default value for <typeparamref name="T"/> if not found.</returns>
    private T GetValue<T>(String name)
    {
        var field = _type.GetField(name, BindingFlags.NonPublic | BindingFlags.Static);
        return field is null
            ? default!
            : field.GetValue(null) is T value
                ? value
                : default!;
    }

    private Boolean? _isPrerelease;
    private Boolean? _isPublicRelease;
    private DateTime? _gitCommitAuthorDate;
    private DateTime? _gitCommitDate;

    /// <summary>
    /// Gets a value indicating whether this is a prerelease version.
    /// </summary>
    public Boolean IsPrerelease => _isPrerelease ??= GetValue<Boolean>("IsPrerelease");

    /// <summary>
    /// Gets a value indicating whether this is a public release version.
    /// </summary>
    public Boolean IsPublicRelease => _isPublicRelease ??= GetValue<Boolean>("IsPublicRelease");

    /// <summary>
    /// Gets the date and time when the commit was authored.
    /// </summary>
    public DateTime GitCommitAuthorDate => _gitCommitAuthorDate ??= GetValue<DateTime>("GitCommitAuthorDate");

    /// <summary>
    /// Gets the date and time when the commit was created.
    /// </summary>
    public DateTime GitCommitDate => _gitCommitDate ??= GetValue<DateTime>("GitCommitDate");

    /// <summary>
    /// Gets the assembly configuration (e.g., "Debug", "Release").
    /// </summary>
    public String AssemblyConfiguration => field ??= GetValue<String>("AssemblyConfiguration");

    /// <summary>
    /// Gets the assembly file version.
    /// </summary>
    public String AssemblyFileVersion => field ??= GetValue<String>("AssemblyFileVersion");

    /// <summary>
    /// Gets the full name of the assembly.
    /// </summary>
    public String AssemblyFullName { get; }

    /// <summary>
    /// Gets the assembly image runtime version.
    /// </summary>
    public String AssemblyImageRuntimeVersion { get; }

    /// <summary>
    /// Gets the assembly informational version.
    /// </summary>
    public String AssemblyInformationalVersion => field ??= GetValue<String>("AssemblyInformationalVersion");

    /// <summary>
    /// Gets the file path of the assembly.
    /// </summary>
    public String AssemblyLocation { get; }

    /// <summary>
    /// Gets the name of the assembly.
    /// </summary>
    public String AssemblyName => field ??= GetValue<String>("AssemblyName");

    /// <summary>
    /// Gets the assembly title.
    /// </summary>
    public String AssemblyTitle => field ??= GetValue<String>("AssemblyTitle");

    /// <summary>
    /// Gets the assembly version.
    /// </summary>
    public String AssemblyVersion => field ??= GetValue<String>("AssemblyVersion");

    /// <summary>
    /// Gets the git commit identifier.
    /// </summary>
    public String GitCommitId => field ??= GetValue<String>("GitCommitId");

    /// <summary>
    /// Gets or sets the NuGet package version.
    /// </summary>
    public String NuGetPackageVersion { get => field ??= GetValue<String>("NuGetPackageVersion"); private set; }

    /// <summary>
    /// Gets the root namespace of the assembly.
    /// </summary>
    public String RootNamespace => field ??= GetValue<String>("RootNamespace");
}
