<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace />
		<AssemblyName>ProvisionData.ResultPattern.Generators.Shared</AssemblyName>
        <TargetFramework>netstandard2.0</TargetFramework>

        <!-- NuGet package metadata -->
        <PackageId>ProvisionData.ResultPattern.Shared</PackageId>
        <PackageTags></PackageTags>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
        <IsPackable>false</IsPackable>
        <IsAotCompatible>false</IsAotCompatible>
        <IsTrimmable>false</IsTrimmable>

        <!-- Analyzer/Source Generator settings -->
        <Analyzer>true</Analyzer>
        <IsRoslynComponent>true</IsRoslynComponent>
        <DevelopmentDependency>true</DevelopmentDependency>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <IsPackable>false</IsPackable>
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>

        <!-- NerdBank.GitVersioning -->
        <NBGV_ThisAssemblyNamespace>ProvisionData.ResultPattern.Generators.Shared.Versioning</NBGV_ThisAssemblyNamespace>
    </PropertyGroup>

    <ItemGroup>
        <AdditionalFiles Include="AnalyzerReleases.Shipped.md" />
        <AdditionalFiles Include="AnalyzerReleases.Unshipped.md" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    </ItemGroup>

</Project>
