<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace />
        <AssemblyName>ProvisionData.ResultPattern.Generators.Shared</AssemblyName>
        <TargetFramework>netstandard2.0</TargetFramework>

        <!-- This is a shared library for analyzers - NOT a standalone package -->
        <PackageId>ProvisionData.ResultPattern.Generators.Shared</PackageId>
        <IsPackable>false</IsPackable>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>

        <!-- Analyzer/Source Generator settings -->
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>

        <!-- NerdBank.GitVersioning -->
        <NBGV_ThisAssemblyNamespace>ProvisionData.ResultPattern.Generators.Shared.Versioning</NBGV_ThisAssemblyNamespace>
    </PropertyGroup>

    <ItemGroup>
        <AdditionalFiles Include="AnalyzerReleases.Shipped.md" />
        <AdditionalFiles Include="AnalyzerReleases.Unshipped.md" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    </ItemGroup>

</Project>
