<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace />
		<AssemblyName>ProvisionData.ResultPattern.Generators.UnitTests</AssemblyName>
		<TargetFramework>net10.0</TargetFramework>

		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<OutputType>Exe</OutputType>

	</PropertyGroup>

	<ItemGroup>
		<Using Include="FluentAssertions" />
		<Using Include="Xunit" />
	</ItemGroup>


	<ItemGroup>
		<PackageReference Include="Bogus" />
		<PackageReference Include="FluentAssertions" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="Serilog" />
		<PackageReference Include="Serilog.Sinks.Debug" />
		<PackageReference Include="Serilog.Sinks.TextWriter" />
		<PackageReference Include="xunit.v3" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="xunit.runner.visualstudio">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="xunit.analyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\ProvisionData.Testing.Integration\ProvisionData.Testing.Integration.csproj" />
		<ProjectReference Include="..\ProvisionData.ResultPattern.UnitTests.CustomErrors\ProvisionData.ResultPattern.UnitTests.CustomErrors.csproj" />
	</ItemGroup>

</Project>
