<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>ProvisionData</RootNamespace>
        <TargetFrameworks>net8.0;net10.0</TargetFrameworks>

        <!-- NuGet package metadata -->
        <PackageId>ProvisionData.Testing</PackageId>
        <PackageTags></PackageTags>
        <PackageReadmeFile>./README.md</PackageReadmeFile>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <IsPackable>false</IsPackable>
        <ErrorReport>send</ErrorReport>
        <IncludeSymbols>true</IncludeSymbols>
        <IncludeSource>true</IncludeSource>

        <!-- Project Specific -->
        <IsAotCompatible>false</IsAotCompatible>
        <IsTrimmable>false</IsTrimmable>
        <OutputType>Exe</OutputType>

        <!-- NerdBank.GitVersioning -->
        <NBGV_ThisAssemblyNamespace>ProvisionData.Testing.Versioning</NBGV_ThisAssemblyNamespace>
    </PropertyGroup>

    <ItemGroup>
        <None Include="./README.md" Pack="true" PackagePath="/" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="xunit.v3" />
        <PackageReference Include="xunit.runner.visualstudio">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ProvisionData.Common\ProvisionData.Common.csproj" />
    </ItemGroup>

</Project>