<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="xunit.v3" />
		<PackageReference Include="xunit.runner.visualstudio" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\ProvisionData.ResultPattern\ProvisionData.ResultPattern.csproj" />
		<ProjectReference Include="..\..\src\ProvisionData.ResultPattern.Generators\ProvisionData.ResultPattern.Generators.csproj" 
		                  OutputItemType="Analyzer" 
		                  ReferenceOutputAssembly="false" />
	</ItemGroup>

</Project>
