<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace />
		<AssemblyName>ProvisionData.ResultPattern</AssemblyName>
		<TargetFrameworks>net8.0;net10.0</TargetFrameworks>

		<!-- NuGet package metadata -->
		<PackageId>ProvisionData.ResultPattern</PackageId>
		<PackageTags></PackageTags>
		<PackageReadmeFile>./README.md</PackageReadmeFile>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<IsPackable>true</IsPackable>
		<ErrorReport>send</ErrorReport>
		<IncludeSymbols>true</IncludeSymbols>
		<IncludeSource>true</IncludeSource>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>

		<!-- Project Specific -->
		<IsAotCompatible>false</IsAotCompatible>
		<IsTrimmable>false</IsTrimmable>

		<!-- Analyzer/Source Generator settings -->
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
		<CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)Generated</CompilerGeneratedFilesOutputPath>

		<!-- NerdBank.GitVersioning -->
		<NBGV_ThisAssemblyNamespace>ProvisionData.ResultPattern.Versioning</NBGV_ThisAssemblyNamespace>
	</PropertyGroup>

	<ItemGroup>
		<None Include=".\ProvisionData.ResultPattern.targets" Pack="true" PackagePath="buildTransitive" />
		<None Include=".\ProvisionData.ResultPattern.props" Pack="true" PackagePath="build" />
		<None Include="..\ProvisionData.ResultPattern.Generators\bin\$(Configuration)\netstandard2.0\ProvisionData.ResultPattern.Generators.dll" Pack="true" PackagePath="analyzers/dotnet/cs" />
		<None Include="..\ProvisionData.ResultPattern.Generators.CodeFixes\bin\$(Configuration)\netstandard2.0\ProvisionData.ResultPattern.Generators.CodeFixes.dll" Pack="true" PackagePath="analyzers/dotnet/cs" />
		<None Include="..\ProvisionData.ResultPattern.Generators.Shared\bin\$(Configuration)\netstandard2.0\ProvisionData.ResultPattern.Generators.Shared.dll" Pack="true" PackagePath="analyzers/dotnet/cs" />
	</ItemGroup>

	<ItemGroup>
		<None Include=".\README.md" Pack="true" PackagePath="/" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<!-- Link to GeneratorConsts so both runtime and generators can use it -->
		<Compile Include="..\ProvisionData.ResultPattern.Generators\ProvisionData\ResultPattern\Generators\Consts.cs" Link="ProvisionData\ResultPattern\Generators\Consts.cs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
		<PackageReference Include="Microsoft.Extensions.Http" />
		<PackageReference Include="Microsoft.Extensions.Options" />
	</ItemGroup>

</Project>
