<Project>
    <PropertyGroup>
        <ProvisionDataResultPatternAnalyzersPath>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)..\analyzers\dotnet\cs'))</ProvisionDataResultPatternAnalyzersPath>
    </PropertyGroup>
    <ItemGroup>
        <Analyzer Include="$(ProvisionDataResultPatternAnalyzersPath)\ProvisionData.ResultPattern.Generators.dll" />
        <Analyzer Include="$(ProvisionDataResultPatternAnalyzersPath)\ProvisionData.ResultPattern.Generators.CodeFixes.dll" />
        <Analyzer Include="$(ProvisionDataResultPatternAnalyzersPath)\ProvisionData.ResultPattern.Generators.Shared.dll" />
    </ItemGroup>
</Project>
