// Provision Data Application Framework
// Copyright (C) 2026 Provision Data Systems Inc.
//
// This program is free software: you can redistribute it and/or modify it under the terms of
// the GNU Affero General Public License as published by the Free Software Foundation, either
// version 3 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY
// without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
// See the GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License along with this
// program. If not, see <https://www.gnu.org/licenses/>.

using ProvisionData.ResultPattern.Generators;
using System.Collections.Concurrent;
using System.Reflection;

namespace ProvisionData.ResultPattern.Infrastructure;

/// <summary>
/// Serves as a registry for all <see cref="Error"/> types and their corresponding error code types.
/// </summary>
/// <remarks>
/// <para>
/// Error types are automatically registered via source-generated ModuleInitializers. Each assembly
/// containing public partial Error classes derived from <see cref="Error"/> will have its errors
/// registered when the assembly is loaded.
/// </para>
/// <para>
/// This means that in most cases, you should not need to manually call the Register method for your
/// custom error types, as they will be registered automatically when the assembly is loaded. The 
/// exception is if you are using custom errors that are not generated by the source generator, in
/// which case you MAY need to call Register for those types to ensure they can be  are properly registered in the lookup table.
/// </para>
/// </remarks>
public static class ErrorCodeRegistry
{
    internal static ConcurrentDictionary<Type, ErrorCode> LookupTable { get; } = new();

    /// <summary>
    /// Registers the specified error ErrorType for use within the application.
    /// </summary>
    /// <remarks>This method initializes the error handling mechanism for the specified error ErrorType, allowing
    /// it to be utilized throughout the application. It is important to ensure that the ErrorType parameter TError is a
    /// valid subclass of Error to avoid runtime exceptions.</remarks>
    /// <typeparam name="TError">The ErrorType of error to register. Must derive from the base class Error.</typeparam>
    public static void Register<TError>()
        where TError : Error
        => _ = GetFor<TError>();

    /// <summary>
    /// Retrieves the <see cref="ErrorCode"/> instance associated with the specified <see cref="Error"/> ErrorType, creating
    /// and registering a new instance if one does not already exist.
    /// </summary>
    /// <typeparam name="TError"></typeparam>
    /// <returns>The singleton <see cref="ErrorCode"/> associated with the specified <see cref="Error"/> ErrorType.</returns>
    public static ErrorCode GetFor<TError>()
        where TError : Error => GetFor(typeof(TError));

    /// <summary>
    /// Retrieves the error code instance associated with the specified ErrorType, creating and registering a new instance if
    /// one does not already exist.
    /// </summary>
    /// <remarks>This method is thread-safe and ensures that only one error code instance is created per ErrorType.
    /// Use a valid, non-null ErrorType to avoid exceptions.</remarks>
    /// <param name="type">The ErrorType for which to retrieve the associated error code. This value must not be null.</param>
    /// <returns>An instance of <see cref="ErrorCode"/> associated with the specified ErrorType. If no instance exists, a new one is
    /// created and added to the registry.</returns>
    internal static ErrorCode GetFor(Type type)
        => LookupTable.GetOrAdd(type, CreateInstance);

    /// <summary>
    /// Removes all entries from the global lookup table, resetting it to an empty state.
    /// </summary>
    /// <remarks>This static method affects the global state of the lookup table. After calling this method,
    /// all previously stored entries are deleted, and subsequent lookups will return default values until new entries
    /// are added. Use caution when calling this method in multi-threaded scenarios, as it may impact other consumers
    /// relying on the lookup table's contents.</remarks>
    public static void Clear() => LookupTable.Clear();

    private static readonly Type ErrorType = typeof(Error);
    private static readonly Type ErrorCodeType = typeof(ErrorCode);
    private static ErrorCode CreateInstance(Type errorType)
    {
        // 0. Validate that the provided type is a subclass of Error
        if (!ErrorType.IsAssignableFrom(errorType))
        {
            throw new ArgumentException($"The errorType must be of a type assignable to '{ErrorType.FullName}'.");
        }

        // 1. Find the Error.Code property
        var errorCodeProp = errorType.GetProperty(GeneratorConsts.ErrorCodeProperty, BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance)
            ?? throw new InvalidOperationException($"Type '{errorType.FullName}' does not contain a '{GeneratorConsts.ErrorCodeProperty}' property.");

        // 1.5 Validate that the Code property is of a type assignable to ErrorCode
        var errorCodeType = errorCodeProp.PropertyType;
        if (!ErrorCodeType.IsAssignableFrom(errorCodeType))
        {
            throw new ArgumentException($"The '{GeneratorConsts.ErrorCodeProperty}' property on type '{errorType.FullName}' must be of a type assignable to '{ErrorCodeType.FullName}'.");
        }

        // 2. Find the static Instance property on the ErrorCode ErrorType
        var errorCodeInstanceProp = errorCodeType.GetProperty(GeneratorConsts.ErrorCodeInstanceProperty, BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.DeclaredOnly | BindingFlags.Static);
        if (errorCodeInstanceProp is not null)
        {
            try
            {
                // Use the singleton instance
                return (ErrorCode)errorCodeInstanceProp.GetValue(null)!;
            }
            catch (Exception ex)
            {
                throw new ResultPatternException($"Retrieving the '{GeneratorConsts.ErrorCodeInstanceProperty}' property value from '{errorCodeType.FullName}' failed.", ex);
            }
        }

        try
        {
            // 3. Fallback: Create a new instance. The error code type should be simple and have a parameterless
            // constructor, so this should be safe. Just means that there will be two instances of the error code.
            // The one created here and the one assigned to the ErrorCode.Instance property. Or maybe not, since
            // we were unable to retrieve it. That might mean that it is a custom error and we may not be able
            // deserialize it properly, but at least we can create an instance to return here.

            // ToDo: When we introduce StrictMode, this should throw instead of playing nice.
            return (ErrorCode)Activator.CreateInstance(errorCodeType)!;
        }
        catch (Exception ex)
        {
            // Cannot do anything because it is probably abstract. Just return.
            throw new ResultPatternException($"Registering {errorType.FullName} failed because {ErrorCodeType.FullName} could not be created.", ex);
        }
    }
}
