// Provision Data Application Framework
// Copyright (C) 2026 Provision Data Systems Inc.
//
// This program is free software: you can redistribute it and/or modify it under the terms of
// the GNU Affero General Public License as published by the Free Software Foundation, either
// version 3 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY
// without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
// See the GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License along with this
// program. If not, see <https://www.gnu.org/licenses/>.

using ProvisionData.ResultPattern.Generators;
using System.Collections.Concurrent;
using System.Reflection;

namespace ProvisionData.ResultPattern.Infrastructure;

/// <summary>
/// Serves as a registry for all <see cref="Error"/> types and their corresponding error code types.
/// </summary>
/// <remarks>
/// <para>
/// Error types are automatically registered via source-generated ModuleInitializers. Each assembly
/// containing public partial Error classes derived from <see cref="Error"/> will have its errors
/// registered when the assembly is loaded.
/// </para>
/// <para>
/// This means that in most cases, you should not need to manually call the Register method for your
/// custom error types, as they will be registered automatically when the assembly is loaded. The 
/// exception is if you are using custom errors that are not generated by the source generator, in
/// which case you MAY need to call Register for those types to ensure they can be  are properly registered in the lookup table.
/// </para>
/// </remarks>
public static class ErrorCodeRegistry
{
    internal static ConcurrentDictionary<Type, ErrorCode> LookupTable { get; } = new();

    /// <summary>
    /// Registers the specified error ErrorType for use within the application.
    /// </summary>
    /// <remarks>This method initializes the error handling mechanism for the specified error ErrorType, allowing
    /// it to be utilized throughout the application. It is important to ensure that the ErrorType parameter TError is a
    /// valid subclass of Error to avoid runtime exceptions.</remarks>
    /// <typeparam name="TError">The ErrorType of error to register. Must derive from the base class Error.</typeparam>
    public static void Register<TError>()
        where TError : Error
        => _ = GetFor<TError>();

    /// <summary>
    /// Retrieves the <see cref="ErrorCode"/> instance associated with the specified <see cref="Error"/> ErrorType, creating
    /// and registering a new instance if one does not already exist.
    /// </summary>
    /// <typeparam name="TError"></typeparam>
    /// <returns>The singleton <see cref="ErrorCode"/> associated with the specified <see cref="Error"/> ErrorType.</returns>
    public static ErrorCode GetFor<TError>()
        where TError : Error => GetFor(typeof(TError));

    /// <summary>
    /// Retrieves the error code instance associated with the specified ErrorType, creating and registering a new instance if
    /// one does not already exist.
    /// </summary>
    /// <remarks>This method is thread-safe and ensures that only one error code instance is created per ErrorType.
    /// Use a valid, non-null ErrorType to avoid exceptions.</remarks>
    /// <param name="type">The ErrorType for which to retrieve the associated error code. This value must not be null.</param>
    /// <returns>An instance of <see cref="ErrorCode"/> associated with the specified ErrorType. If no instance exists, a new one is
    /// created and added to the registry.</returns>
    internal static ErrorCode GetFor(Type type)
        => LookupTable.GetOrAdd(type, CreateInstance);

    /// <summary>
    /// Removes all entries from the global lookup table, resetting it to an empty state.
    /// </summary>
    /// <remarks>This static method affects the global state of the lookup table. After calling this method,
    /// all previously stored entries are deleted, and subsequent lookups will return default values until new entries
    /// are added. Use caution when calling this method in multi-threaded scenarios, as it may impact other consumers
    /// relying on the lookup table's contents.</remarks>
    public static void Clear() => LookupTable.Clear();

    private static readonly Type ErrorType = typeof(Error);
    private static readonly Type ErrorCodeType = typeof(ErrorCode);
    private const String NotEmpty = "Not Empty";

    private static ErrorCode CreateInstance(Type errorType)
    {
        // Validate that the provided type is a subclass of Error
        if (ErrorType.IsAssignableFrom(errorType))
        {
            throw new ArgumentException($"Type '{errorType.FullName}' must derive from '{ErrorType.FullName}'", nameof(errorType));
        }

        // Find the Code property
        var errorCodeProp = errorType.GetProperty(Consts.ErrorCode, BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance)
            ?? throw new ArgumentException($"Type '{errorType.FullName}' must have a '{Consts.ErrorCode}' property.", nameof(errorType));

        try
        {
            // Create an instance of the errorType
            var error = Activator.CreateInstance(errorType, NotEmpty);

            // Get the value of the Code property
            var codeValue = errorCodeProp.GetValue(error)
                ?? throw new ArgumentException($"Type '{errorType.FullName}' must have a non-null '{Consts.ErrorCode}' property value.", nameof(errorType));

            // Get the type of the ErrorCode
            var errorCodeType = codeValue.GetType();
            if (ErrorCodeType.IsAssignableFrom(errorCodeType))
            {
                throw new ArgumentException($"The '{Consts.ErrorCode}' property of type '{errorType.FullName}' must be a derivative of {ErrorCodeType.FullName}.", nameof(errorType));
            }

            // Get the Instance property
            var instanceProp = errorCodeType.GetField(Consts.Instance, BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static);
            if (instanceProp is null)
            {
                // Fallback: Create a new instance. The error code type should be simple and have a parameterless
                // constructor, so this should be safe. Just means that there will be two instances of the error code.
                // The one created here and the one assigned to the ErrorCode.Instance property. Or maybe not, since
                // we were unable to retrieve it. That might mean that it is a custom error and we may not be able
                // deserialize it properly, but at least we can create an instance to return here.
                if (Activator.CreateInstance(errorCodeType) is ErrorCode fallback)
                {
                    return fallback;
                }

                throw new ArgumentException($"The type {errorType.FullName}.{errorCodeType.FullName} must have a static '{Consts.Instance}' field with a not-null value, or a parameterless constructor.", nameof(errorType));
            }

            // Get the value of the Instance property
            if (instanceProp.GetValue(null) is not ErrorCode value)
            {
                throw new ArgumentException($"The static '{Consts.Instance}' field of type '{errorCodeType.FullName}' must be of type '{ErrorCodeType.FullName}'.", nameof(errorType));
            }

            return value;
        }
        catch (MissingMethodException ex)
        {
            throw new ResultPatternException($"Registering {errorType.FullName} failed because {ErrorCodeType.FullName} could not be created.", ex);
        }
    }
}
