<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace />
		<AssemblyName>ProvisionData.ResultPattern.Generators.CodeFixes</AssemblyName>
        <TargetFramework>netstandard2.0</TargetFramework>

        <!-- NuGet package metadata -->
        <PackageId>ProvisionData.ResultPattern.CodeFixes</PackageId>
        <PackageTags></PackageTags>

        <!--
		These are settings specfic for analyzers/code fixes/source generators. We set IsPackable to false
		to prevent packing this project as a separate NuGet package, but we still want to include the
		assembly in the main package's analyzers folder.
		-->
        <Analyzer>true</Analyzer>
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <IsRoslynComponent>true</IsRoslynComponent>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
        <DevelopmentDependency>true</DevelopmentDependency>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <PrivateAssets>all</PrivateAssets>
        <IsPackable>false</IsPackable>
        <IsAotCompatible>false</IsAotCompatible>
        <IsTrimmable>false</IsTrimmable>

        <!-- NerdBank.GitVersioning -->
        <NBGV_ThisAssemblyNamespace>ProvisionData.ResultPattern.Generators.CodeFixes.Versioning</NBGV_ThisAssemblyNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ProvisionData.ResultPattern.Generators.Shared\ProvisionData.ResultPattern.Generators.Shared.csproj" PrivateAssets="all" />
    </ItemGroup>

</Project>
