<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>ProvisionData</RootNamespace>
        <TargetFrameworks>net8.0;net10.0</TargetFrameworks>

        <!-- NuGet package metadata -->
        <PackageId>ProvisionData.WebApi</PackageId>
        <PackageTags></PackageTags>
        <PackageReadmeFile>./README.md</PackageReadmeFile>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <IsPackable>true</IsPackable>
        <ErrorReport>send</ErrorReport>
        <IncludeSymbols>true</IncludeSymbols>
        <IncludeSource>true</IncludeSource>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>

        <!-- Project Specific -->
        <IsAotCompatible>True</IsAotCompatible>
        <IsTrimmable>False</IsTrimmable>

        <!-- NerdBank.GitVersioning -->
        <NBGV_ThisAssemblyNamespace>ProvisionData.WebApi.Versioning</NBGV_ThisAssemblyNamespace>
    </PropertyGroup>

    <ItemGroup>
        <None Include="./README.md" Pack="true" PackagePath="/" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ProvisionData.ResultPattern\ProvisionData.ResultPattern.csproj" />
    </ItemGroup>

</Project>
