<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <RootNamespace />
        <TargetFramework>net10.0</TargetFramework>

        <!-- NuGet package metadata -->
        <IsPackable>false</IsPackable>
        <IsAotCompatible>false</IsAotCompatible>
        <IsTrimmable>false</IsTrimmable>

        <!-- NerdBank.GitVersioning -->
        <NBGV_ThisAssemblyNamespace>ProvisionData.HaloPSA.ApiClient.ModelGenerator.Versioning</NBGV_ThisAssemblyNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Humanizer.Core" />
        <PackageReference Include="Microsoft.Extensions.Hosting" />
    </ItemGroup>

    <ItemGroup>
        <None Update="custom-fields-config.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
