// Provision Data Application Framework
// Copyright (C) 2026 Provision Data Systems Inc.
//
// This program is free software: you can redistribute it and/or modify it under the terms of
// the GNU Affero General Public License as published by the Free Software Foundation, either
// version 3 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY
// without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
// See the GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License along with this
// program. If not, see <https://www.gnu.org/licenses/>.

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;
using ThisAssembly = ProvisionData.ResultPattern.Generators.Versioning.ThisAssembly;

namespace ProvisionData.ResultPattern.Generators;

[Generator]
public sealed partial class CustomErrorSourceGenerator/*(ILogger logger)*/ : IIncrementalGenerator
{
    //private readonly ILogger _logger = logger;

    //[LoggerMessage(EventId = 0, Level = LogLevel.Critical, Message = "Could not open socket to `{HostName}`")]
    //public partial void CouldNotOpenSocket(String hostName);

    private static String GeneratorName => nameof(@CustomErrorSourceGenerator);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // STEP 1: Find all class declarations with "partial" and ": Error"
        var errorClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidate(node),
                transform: static (ctx, _) => GetErrorSymbol(ctx))
            .Where(static m => m is not null);

        // STEP 2: Collect them into an array
        var collected = errorClasses.Collect();

        // STEP 3: Generate code
        context.RegisterSourceOutput(collected, static (spc, errors) =>
        {
            ErrorCodesGenerator(spc, errors!);
            ErrorConstructorsGenerator(spc, errors!);
            //ErrorTypeRegistryGenerator(spc, errors!);
            //ErrorPolymorphismHookGenerator(spc, errors!);
        });
    }

    private static Boolean IsCandidate(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax cds
            && cds.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword));
    }

    private static INamedTypeSymbol? GetErrorSymbol(GeneratorSyntaxContext ctx)
    {
        var cds = (ClassDeclarationSyntax)ctx.Node;

        if (ctx.SemanticModel.GetDeclaredSymbol(cds) is not INamedTypeSymbol symbol)
        {
            return null;
        }

        // Must derive from Error
        var baseType = symbol.BaseType;

        while (baseType is not null)
        {
            var fullName = baseType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            if (fullName == GeneratorConsts.FullyQualifiedErrorTypeName)
            {
                return symbol;
            }

            baseType = baseType.BaseType;
        }

        return null;
    }

    private static String Header(String passName)
    {
        var utcTimestamp = DateTime.UtcNow.ToString("yyyy-MM-ddTHH:mm:ssZ");

        return
            $"""
            // <auto-generated>
            //   This file was brought to you by {ThisAssembly.AssemblyName}
            //   Version: {ThisAssembly.AssemblyInformationalVersion}
            //   Generator: {GeneratorName}
            //   Pass: {passName}
            //   Generated at: {utcTimestamp}
            //
            //   DO NOT EDIT THIS FILE BY HAND OR THE WORLD MAY END!
            //   (Seriously. The generator will overwrite your changes anyway.)
            //
            // </auto-generated>

            """;
    }

    private static void ErrorCodesGenerator(SourceProductionContext context, ImmutableArray<INamedTypeSymbol> errors)
    {
        var sb = new StringBuilder();
        sb.AppendLine(Header(nameof(ErrorCodesGenerator)));
        foreach (var error in errors)
        {

            var ns = error.ContainingNamespace.IsGlobalNamespace
                ? null
                : error.ContainingNamespace.ToDisplayString();

            var errorName = error.Name;
            var codeName = errorName + GeneratorConsts.ErrorCodeSuffix;

            if (ns is not null)
            {
                sb.AppendLine($"namespace {ns}");
                sb.AppendLine("{");
            }

            sb.AppendLine($"#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member");
            sb.AppendLine($"    internal sealed class {codeName} : global::{GeneratorConsts.ResultPatternNamespace}.ErrorCode");
            sb.AppendLine("    {");
            sb.AppendLine($"        public static readonly {codeName} Instance = new();");
            sb.AppendLine($"        protected override System.String Name => \"{errorName}\";");
            sb.AppendLine("    }");
            sb.AppendLine($"#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member");

            if (ns is not null)
            {
                sb.AppendLine("}");
            }

            sb.AppendLine();
        }

        context.AddSource(GeneratorConsts.GeneratedErrorCodesFilename, sb.ToString());
    }

    private static void ErrorConstructorsGenerator(SourceProductionContext context, ImmutableArray<INamedTypeSymbol> errors)
    {
        var sb = new StringBuilder();
        sb.AppendLine(Header(nameof(ErrorConstructorsGenerator)));

        foreach (var error in errors)
        {
            var ns = error.ContainingNamespace.IsGlobalNamespace
                ? null
                : error.ContainingNamespace.ToDisplayString();

            var errorName = error.Name;
            var codeName = errorName + GeneratorConsts.ErrorCodeSuffix;

            // Find all properties (typically marked with 'required')
            var properties = error.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => !p.IsStatic && p.SetMethod is not null)
                .ToList();

            if (ns is not null)
            {
                sb.AppendLine($"namespace {ns}");
                sb.AppendLine("{");
            }

            sb.AppendLine($"#pragma warning disable CS1591 // Suppresses Missing XML comment for publicly visible type or member");
            sb.AppendLine($"public sealed partial class {errorName}");
            sb.AppendLine("{");

            // Generate constructor
            sb.AppendLine($"    public {errorName}(");

            // Build parameter list from properties
            var paramList = new List<String>();
            foreach (var prop in properties)
            {
                var type = prop.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
                var paramName = LowerFirst(prop.Name);
                paramList.Add($"{type} {paramName}");
            }

            paramList.Add("System.String description");

            sb.AppendLine($"        {String.Join(",\r\n        ", paramList)})");
            sb.AppendLine($"        : base({codeName}.Instance, description)");
            sb.AppendLine("    {");

            // Initialize properties from parameters
            foreach (var prop in properties)
            {
                var paramName = LowerFirst(prop.Name);
                sb.AppendLine($"        this.{prop.Name} = {paramName};");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine($"#pragma warning restore CS1591 // Restores Missing XML comment for publicly visible type or member");

            if (ns is not null)
            {
                sb.AppendLine("}");
            }

            sb.AppendLine();
        }

        context.AddSource(GeneratorConsts.GeneratedErrorConstructorsFilename, sb.ToString());
    }

    private static void ErrorTypeRegistryGenerator(SourceProductionContext context, ImmutableArray<INamedTypeSymbol> errors)
    {
        if (errors.Length == 0)
        {
            return; // No errors to register
        }

        var sb = new StringBuilder();
        sb.AppendLine(Header(nameof(ErrorTypeRegistryGenerator)));

        // Get the namespace of the first error (they should all be in the same assembly)
        var ns = errors[0].ContainingNamespace.IsGlobalNamespace
            ? null
            : errors[0].ContainingNamespace.ToDisplayString();

        if (ns is not null)
        {
            sb.AppendLine($"namespace {ns};");
        }

        sb.AppendLine("#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member");
        sb.AppendLine($"    internal static class {GeneratorConsts.ErrorTypeRegistryInitializerClassName}");
        sb.AppendLine("    {");
        sb.AppendLine("        [System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("        internal static void Initialize()");
        sb.AppendLine("        {");
        sb.AppendLine("            Console.WriteLine(\"Initializing ErrorCodeRegistry...\");");

        foreach (var error in errors)
        {
            var fullName = error.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                .Replace("global::", "");
            sb.AppendLine($"            global::{GeneratorConsts.ResultPatternNamespace}.Infrastructure.{GeneratorConsts.ErrorTypeRegistryClassName}.Register<{fullName}>();");
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member");

        context.AddSource(GeneratorConsts.ErrorTypeRegistryInitializerFilename, sb.ToString());
    }

    private static void ErrorPolymorphismHookGenerator(SourceProductionContext context, ImmutableArray<INamedTypeSymbol> errors)
    {
        if (errors.Length == 0)
        {
            return;
        }

        var sb = new StringBuilder();
        sb.AppendLine(Header(nameof(ErrorPolymorphismHookGenerator)));
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Text.Json.Serialization.Metadata;");
        sb.AppendLine();
        sb.AppendLine($"internal static class {GeneratorConsts.ErrorPolymorphismInitializerClassName}");
        sb.AppendLine("{");
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    internal static void Initialize()");
        sb.AppendLine("    {");
        sb.AppendLine("        Console.WriteLine(\"Initializing ErrorPolymorphism...\");");
        sb.AppendLine($"        global::{GeneratorConsts.ResultPatternNamespace}.Infrastructure.{GeneratorConsts.ErrorJsonPolymorphismClassName}.Register(Configure);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static void Configure(JsonTypeInfo ti)");
        sb.AppendLine("    {");
        sb.AppendLine($"        if (ti.Type == typeof(global::{GeneratorConsts.ResultPatternNamespace}.ErrorCode))");
        sb.AppendLine("        {");
        sb.AppendLine("            ti.PolymorphismOptions ??= new JsonPolymorphismOptions");
        sb.AppendLine("            {");
        sb.AppendLine($"                {GeneratorConsts.TypeDiscriminatorPropertyName} = \"$code\"");
        sb.AppendLine("            };");

        foreach (var error in errors.Distinct(SymbolEqualityComparer.Default))
        {
            if (error is null)
            {
                continue;
            }

            var errorName = error.Name;
            var codeName = errorName + "Code";
            var ns = error.ContainingNamespace.IsGlobalNamespace
                ? null
                : error.ContainingNamespace.ToDisplayString();

            var fullCodeType = (ns is null ? codeName : ns + "." + codeName);
            var discriminator = $"{fullCodeType}:v1";

            sb.AppendLine(
                $"            ti.PolymorphismOptions.DerivedTypes.Add(new JsonDerivedType(typeof({fullCodeType}), \"{discriminator}\"));");
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource(GeneratorConsts.ErrorPolymorphismInitializerFilename, sb.ToString());
    }

    private static String UpperFirst(String name)
        => String.IsNullOrEmpty(name) ? name : Char.ToUpperInvariant(name[0]) + name.Substring(1);

    private static String LowerFirst(String name)
        => String.IsNullOrEmpty(name) ? name : Char.ToLowerInvariant(name[0]) + name.Substring(1);
}
